### ISSUE TITLE
Make org.apache.maven.reporting/maven-reporting-exec scope test

### ISSUE THREAD

**Issue by kennyjwilli** [xypron/jcobyla#2]
Is there a reason to have `org.apache.maven.reporting/maven-reporting-exec` as a runtime dependency? If not, I suggest changing its `scope` to `"test"`. Happy to submit a PR if you're interested.

**Comment by xypron** [comment]
@kennyjwilli 
Thanks for reporting. I have removed the superfluous dependency in version 1.3 which I just uploaded to Maven Central.
